### ISSUE TITLE
Compilation issue on macOS

### ISSUE THREAD

**Issue by mkhorton** [pmla/auguste#1]
There seem to be compilation errors on macOS, this has been a common issue with several codes so should be an easy fix in your `setup.py`:

```
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
```

See here for a fix: https://github.com/pandas-dev/pandas/blob/8e4424fbcfc98d23085ddbcf8765946bc85da035/setup.py#L477 (thanks @utf)

Also, I was wondering if you were planning to release this on PyPI for a normal `pip install`? This looks like a great code, would look forward to using it!

**Comment by pmla** [comment]
Thanks for making an issue!
I have made some changes which should hopefully fix the problem:
* removed dependency on C++11
* fixed the `setup.py`

Let me know if it works on your end. I am going to try and get Travis CI working so that the macOS build will be tested automatically. Also unit tests.

I have uploaded the project to PyPI and updated the README. Thanks for the suggestion. Other issues or suggestions are always welcome.
